language: generic 
sudo: required 

services:
  - docker 

before_install:
  - docker build -t sujnanarai/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sujnanarai/react-test npm run test -- --coverage

after_success:
  - docker build -t sujnanarai/multi-client ./client
  - docker build -t sujnanarai/multi-nginx ./nginx
  - docker build -t sujnanarai/multi-nginx ./server
  - docker build -t sujnanarai/multi-worker ./worker
  # Login to the Docker CLI. Create DOCKER_USERID (docker hub userid) and DOCKER_PASSWORD (docker hub passowrd) in Travis-ci.org for the git repostitory. 
  - echo "$DOCKER_PASSWORD" | docker login - u "$DOCKER_USERID" --password-stdin
  # Take those images and push tem to the Docker Hub
  - docker push sujnanarai/multi-client
  - docker push sujnanarai/multi-nginx
  - docker push sujnanarai/multi-nginx
  - docker push sujnanarai/multi-worker